---
title: "Lab 02 - Hello IDS!"
author: "Felix Gibbons"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Felix", "Suhas", "Nathan", 
           "Ed", "Roger"),
  github_username = c("felix1414828", "suhasvnadimpalli-droid", "nathanc1/2","evertigen", "RogerWang6"), 
  colour = c("powderblue", "navyblue", "yellow", 
             "pink", "lightblue"),
  hobby = c("Sailing", "Football", "Hiking", 
            "Rugby", "Photography"),
  favourite_number = c(4, 48, 9, 8, 6)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

